modLoader="javafml" #mandatory
loaderVersion="${forgefmlrange}"
license="${license}"
logoFile="pack.png" #optional
issueTrackerURL="https://github.com/SrRapero720/watermedia/issues"
displayTest="IGNORE_SERVER_VERSION"
[[mods]]
    modId="${id}"
    version="${version}"
    displayName="${name}"
    displayTest="IGNORE_SERVER_VERSION"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/watermedia"
    logoFile="pack.png" #optional
    credits="${credits}"
    authors="${authors}"
    description='''${description}'''