modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/SrRapero720/watermedia/issues"
[[mods]]
    modId="watermedia"
    version="${file.jarVersion}"
    displayName="WATERMeDIA"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/watermedia"
    logoFile="pack.png" #optional
    credits="VLC to VideoLAN team, VLCJ by caprica, VLCJ discovery by CreativeMD"
    authors="SrRapero720 and Goedix"
    description='''
    Library to expand Minecraft entertainment using multimedia content
    Powered by WATERCoRE
    '''
[[dependencies.watermedia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,)" # ON FORGE ONLY SUPPORTS 1.17 (MIN JAVA IS 15 FEATURES)
    ordering="NONE"
    side="CLIENT"