modLoader="javafml" #mandatory
loaderVersion="${fgrange}"
license="${modlicense}"
logoFile="pack.png" #optional
issueTrackerURL="https://github.com/SrRapero720/watermedia/issues"
[[mods]]
    modId="${modid}"
    version="${modversion}"
    displayName="${modname}"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/watermedia"
    logoFile="pack.png" #optional
    credits="${modcredits}"
    authors="${modauthors}"
    description='''${moddescription}'''
[features.${mod_id}]
    javaVersion="[8,)"